const cars = [
    {
      id : 0,
      name: "Volkswagen Virtus",
      type: "sedan",
      price: 11.4,
      imgSrc: "https://s1.paultan.org/image/2017/11/Volkswagen-Virtus-Brazil-1.jpg",
      seater: 5,
    },
    {
      id : 1,
      name: "Tata Nexon",
      type: "SUV",
      price: 10,
      imgSrc: "https://www.autobics.com/wp-content/uploads/2017/09/tata-nexon-moroccan-blue-front-left-pr-.jpg",
      seater: 5,
    },
    {
      id : 2,
      name: "Hyundai Creta",
      type: "SUV",
      price: 10,
      imgSrc: "https://tse4.mm.bing.net/th?id=OIP.HHgsZol10P5joMeNignFeAHaFr&pid=Api&P=0&h=180",
      seater: 5,
    },
    {
      id : 3,
      name: "Hyundai Aura",
      type: "sedan",
      price: 7,
      imgSrc: "https://tse3.mm.bing.net/th?id=OIP.xr9w67dyuEzpAtg5RuWSUgHaE8&pid=Api&P=0&h=180",
      seater: 5,
    },
    {
      id : 4,
      name: "Tata Punch",
      type: "SUV",
      price: 6,
      imgSrc: "https://tse3.mm.bing.net/th?id=OIP.8P_38YmWEnPjDFK0YMViTAHaEK&pid=Api&P=0&h=180",
      seater: 5,
    },
    {
      id : 5,
      name: "Maruti Swift",
      type: "Hatchback",
      price: 6,
      imgSrc: "https://tse1.mm.bing.net/th?id=OIP.OYUnnJJPJ0wzXmwyr9ZWdgHaE8&pid=Api&P=0&h=180",
      seater: 5,
    },
    {
      id : 6,
      name: "Tata Tiago",
      type: "Hatchback",
      price: 5.6,
      imgSrc: "http://stat.overdrive.in/wp-content/odgallery/2018/02/40336_tata_tiago_ev.jpg",
      seater: 5,
    },
    {
      id : 7,
      name: "Hyundai i20",
      type: "Hatchback",
      price: 7,
      imgSrc: "https://tse4.mm.bing.net/th?id=OIP.pr7mOFlxeBH8pJVph7gv4gHaE8&pid=Api&P=0&h=180",
      seater: 5,
    },
    {
      id : 8,
      name: "Hyundai Exter",
      type: "SUV",
      price: 6,
      imgSrc: "https://static.autox.com/uploads/2023/05/Hyundai-Exter.jpg",
      seater: 5,
    },
    {
      id : 9,
      name: "Toyota Fortuner",
      type: "SUV",
      price: 32.2,
      imgSrc: "https://tse4.mm.bing.net/th?id=OIP.ljwaYYtfoBVdnB2aNvTWNAHaFj&pid=Api&P=0&h=180",
      seater: 7,
    },
    {
      id : 10,
      name: "Maruti Baleno",
      type: "Hatchback",
      price: 6.5,
      imgSrc: "https://stat.overdrive.in/wp-content/odgallery/2016/01/28131_DSC_7736.JPG",
      seater: 5,
    },
    {
      id : 11,
      name: "Mahindra Thar",
      type: "SUV",
      price: 10,
      imgSrc: "https://tse1.mm.bing.net/th?id=OIP.fp6CeGYeoEjxo1J1ppwBNgHaEL&pid=Api&P=0&h=180",
      seater: 5,
    },
    {
      id : 12,
      name: "Maruti Alto 800",
      type: "Hatchback",
      price: 4,
      imgSrc: "https://www.rushlane.com/wp-content/uploads/2019/12/new-2020-maruti-alto-800-touchscreen-launch-price-2.jpg",
      seater: 5,
    },
    {
      id : 13,
      name: "Toyota Camry",
      type: "sedan",
      price: 46,
      imgSrc: "https://tse1.mm.bing.net/th?id=OIP.Ix-NLxbzwLC3Rs-0-zxjFQHaEA&pid=Api&P=0&h=180",
      seater: 5,
    },
    {
      id : 14,
      name: "Honda City",
      type: "sedan",
      price: 12,
      imgSrc: "https://mygadgetreviewer.com/wp-content/uploads/2020/04/honda-city-2020-exterior-images-e1586943213836.jpg",
      seater: 5,
    },
    {
      id : 15,
      name: "Kia Seltos",
      type: "SUV",
      price: 11,
      imgSrc: "https://news.maxabout.com/wp-content/uploads/2019/07/Kia-Seltos-Color-3.jpg",
      seater: 5,
    },
    {
      id : 16,
      name: "Maruti Dzire",
      type: "sedan",
      price: 6.5,
      imgSrc: "https://tse4.mm.bing.net/th?id=OIP.gFOjWZSKZYcdZeuyOOtdEwHaFj&pid=Api&P=0&h=180",
      seater: 5,
    },
    {
      id : 17,
      name: "Audi A4",
      type: "sedan",
      price: 43.4,
      imgSrc: "https://tse1.mm.bing.net/th?id=OIP.tkxqH_b-VqP-Ky2BDnxuCwHaD8&pid=Api&P=0&h=180",
      seater: 5,
    },
    {
      id : 18,
      name: "Maruti Wagon R",
      type: "Hatchback",
      price: 5.9,
      imgSrc: "https://tse1.mm.bing.net/th?id=OIP.LbzRjOsPlhFHL28nvYdp8QHaE8&pid=Api&P=0&h=180",
      seater: 5,
    },
    {
      id : 19,
      name: "Honda Amaze",
      type: "sedan",
      price: 7.3,
      imgSrc: "https://tse4.mm.bing.net/th?id=OIP.5yLvIY-ADYKglqSm7eoN7wHaE6&pid=Api&P=0&h=180",
      seater: 5,
    },
];
  
export {cars};